### ISSUE TITLE
Cannot find vkGetPhysicalDeviceWin32PresentationSupportKHR?

### ISSUE THREAD

**Issue by david7a68** [ParticlePeter/Erupted-V2#2]
I just tried updating my dependencies for a project, and implemented the documented changes.

For whatever reason, dmd can't find `vkGetPhysicalDeviceWin32PresentationSupportKHR` even if it's in the same module.

e.g.:
```d
import erupted.platform_extensions;

version (Windows) {
    import core.sys.windows.windows;
    mixin Platform_Extensions!VK_USE_PLATFORM_WIN32_KHR;
}
pragma(msg, typeof(vkGetPhysicalDeviceWin32PresentationSupportKHR));
```

I'm not quite sure what's going on. I moved the module to a separate project with just this module, but the error persists. A quick look-see through erupted's source seems to indicate that it's on my side, but the module is so simple that there's not much that could go wrong.

**Comment by ParticlePeter** [comment]
It doen't work for me either, looking into it.

**Comment by ParticlePeter** [comment]
Apologies  for your inconvenience, it is fixed, but I moved back to original ErupteD with version v2.0. The issue was that Vulkan uses feater names, which are grouped into alias sequnces, as well, overwriting their definition. So the only coded mixed in were type definitions. Please note that the module above is not present any more, it created trouble on posix. The same module can be found in ErupteD `examples/platform` but you need to copy it into your project, as it will not be build by default. Also note that the VK_ prefix has been dropped. This is explained in in the new ErupteD readme. Thanks for your patience.

**Comment by ParticlePeter** [comment]
Can this be closed?

**Comment by david7a68** [comment]
Yes. There's no more action to be taken.

Thanks for your quick response.
