### ISSUE TITLE
Callbacks should be `extern(C)`

### ISSUE THREAD

**Issue by AntonMeep** [ParticlePeter/Erupted-V2#3]
(This is the problem I have with erupted-v1, but I decided to post it here).

I was having a problem with VK_EXT_debug_report extension when *nothing* was passed to my callback (Everything is 0 and pointers point to 0x1).

After digging deeper and trying to mark `PFN_vkDebugReportCallbackEXT`  as a `extern(C)` it worked. So shouldn't other callbacks be marked `extern(C)` as well?

Also, removing `@nogc` attribute worked too meaning that I can use non-nogc code in my callbacks. I'm not sure how safe it is (both memory-safe and thread-safe), but it works flawlessly for me.

Question is: add `extern(C)` for callbacks and remove `@nogc`?

**Comment by ParticlePeter** [comment]
Don't know if you have mentioned, [ErupteD will continue](https://forum.dlang.org/thread/tnlbjwwakuisszumgzdi@forum.dlang.org). Sorry for your inconvenience, but it is better when we move any further issues there. ErupteD-V1 will be deprecated :-) and eventually destroyed. V2 will stay for me getting the auto building and testing running.

This is wired. The whole module is marked as `extern(System):` right on top of the module. This translates to extern(C) on Posix, and extern(Windows) on windows. See [this](https://dlang.org/spec/attribute.html#linkage), the last but one sentence of the first paragraph is explicitly defining that behavior. It works for me on windows, and it has been this way since the beginning, I guess somebody else would have had an issues as well. Are you sure that it works with your workflow? Can I see your code  somewhere?

To @nogc, for vulkan itself its irrelevant, it calls into C which never has a GC. However, it is necessary for the callers of ErupteD functions which are marked @nogc. They would not be allowed to call ErupteD functions if that attribute would be missing.

**Comment by AntonMeep** [comment]
@ParticlePeter Thanks! Indeed, I didn't noticed `extern(System)` because I moved `PFN_vkDebugReportCallbackEXT` to the top of the module so I could mark it as non-`@nogc`.

I understand why these callbacks are marked as `@nogc`, maybe in the future it would be possible to do something about it (i.e. if user's code is marked as `@nogc` then erupted functions are `@nogc` too, but when user's code uses GC, erupted functions are non-`@nogc` as well)

Anyway, thanks for the help, I'll stick with my own fork (which just moves this one `PFN_vkDebugReportCallbackEXT` to the top of the module and marks it as `nothrow extern(C)`.

**Comment by ParticlePeter** [comment]
@nogc means that no function with this attribute is allowed to GC allocate, and the Vulkan functions don't. But they still can be called from functions which may GC allocate. So, just out of curiosity, what do you think would happen if @nogc would be removed?

**Comment by AntonMeep** [comment]
Talking about callbacks here. If callback is marked as `@nogc`, it cannot use GC at all. Meaning that no fancy `writeln` would work, just plain `printf` and co.

**Comment by ParticlePeter** [comment]
Ah, getting it, sorry, you wanna print in the callback. You can use a try catch block around writeln, or better use printf like [here](https://github.com/ParticlePeter/LBMethoD/blob/538237403db5fc7149be7b2392d1b2065a113e5b/source/initialize.d#L19).

**Comment by ParticlePeter** [comment]
You can pretty much get the same out of printf, its just not so comfortable, but more efficient.

**Comment by AntonMeep** [comment]
try catch block helps with `nothrow`, `@nogc` is different, there is no simple way to hack around it.

I don't like printf - I care about convenience more than performance. In my projects I tend to use `vibe.core.log` for my logging/debugging purposes.

Hey-hey, I found a way around that `@nogc` thing. Looks like it is possible to just `cast` GC function to `@nogc`. I'll test if it works.

UPD: It *does* work. I can finally use latest version from dub instead of git submodule. Thanks
